require('dotenv').config();
const http = require('http');
const TelegramBot = require('node-telegram-bot-api');
const { query } = require('./db');

const TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:4000';

if (!TOKEN) {
  console.error('❌ TELEGRAM_BOT_TOKEN is not set. The bot cannot start.');
  process.exit(1);
}

// Render's free tier only supports "web" services, not background workers.
// This bot uses Telegram long-polling (no inbound webhook needed), so we just
// need to bind a port and answer health checks to keep Render happy — the
// actual bot logic below is unaffected.
const PORT = process.env.PORT || 10000;
http
  .createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('Smart Study Exchange Telegram bot is running.\n');
  })
  .listen(PORT, () => {
    console.log(`🌐 Health check server listening on port ${PORT}`);
  });

const bot = new TelegramBot(TOKEN, { polling: true });

console.log('🤖 Smart Study Exchange Telegram bot is running (polling mode).');

// ---------------------------------------------------------------------------
// /start — greet the user and explain how to link their account
// ---------------------------------------------------------------------------
bot.onText(/\/start/, (msg) => {
  bot.sendMessage(
    msg.chat.id,
    `👋 Welcome to *Smart Study Exchange*!\n\n` +
      `Link your account first:\n` +
      `1️⃣ Open the web app → Profile → "Link Telegram"\n` +
      `2️⃣ Copy the code shown\n` +
      `3️⃣ Send me: \`/link YOUR_CODE\`\n\n` +
      `Once linked, try:\n` +
      `🔎 \`/search <topic>\` — keyword search notes\n` +
      `🧠 \`/smartsearch <topic>\` — AI semantic search\n` +
      `📄 \`/summarize <note title or ID>\` — get a note's AI summary\n` +
      `📊 \`/mynotifications\` — see recent notifications`,
    { parse_mode: 'Markdown' }
  );
});

// ---------------------------------------------------------------------------
// /link <code> — redeem the one-time code generated by the web app
// ---------------------------------------------------------------------------
bot.onText(/\/link (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const code = match[1].trim().toUpperCase();

  try {
    const { rows } = await query(
      'SELECT * FROM telegram_sessions WHERE link_code = $1 AND linked_at IS NULL',
      [code]
    );
    const session = rows[0];

    if (!session) {
      return bot.sendMessage(chatId, '❌ Invalid or already-used link code. Generate a new one from your profile.');
    }

    await query(
      'UPDATE telegram_sessions SET chat_id = $1, linked_at = now(), link_code = NULL WHERE id = $2',
      [String(chatId), session.id]
    );

    bot.sendMessage(chatId, '✅ Your Telegram account is now linked! You will receive notifications here, and can use /search, /smartsearch, /summarize.');
  } catch (err) {
    console.error(err);
    bot.sendMessage(chatId, '⚠️ Something went wrong linking your account. Please try again.');
  }
});

async function requireLinkedUser(chatId) {
  const { rows } = await query('SELECT user_id FROM telegram_sessions WHERE chat_id = $1', [String(chatId)]);
  return rows[0]?.user_id || null;
}

// ---------------------------------------------------------------------------
// /search <query> — FR18: keyword search exposed via bot
// ---------------------------------------------------------------------------
bot.onText(/\/search (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const q = match[1].trim();

  try {
    const res = await fetch(`${API_BASE_URL}/api/search?q=${encodeURIComponent(q)}&mode=keyword&limit=5`);
    const data = await res.json();

    if (!data.results?.length) {
      return bot.sendMessage(chatId, `No notes found for "${q}".`);
    }

    const lines = data.results.map((n, i) => `${i + 1}. *${n.title}* (${n.course_code || 'N/A'})`);
    bot.sendMessage(chatId, `🔎 Results for "${q}":\n\n${lines.join('\n')}`, { parse_mode: 'Markdown' });
  } catch (err) {
    console.error(err);
    bot.sendMessage(chatId, '⚠️ Search failed. Please try again later.');
  }
});

// ---------------------------------------------------------------------------
// /smartsearch <query> — FR18: semantic search exposed via bot
// ---------------------------------------------------------------------------
bot.onText(/\/smartsearch (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const q = match[1].trim();

  try {
    const res = await fetch(`${API_BASE_URL}/api/search?q=${encodeURIComponent(q)}&mode=smart&limit=5`);
    const data = await res.json();

    if (!data.results?.length) {
      return bot.sendMessage(chatId, `No conceptually related notes found for "${q}".`);
    }

    const lines = data.results.map((n, i) => `${i + 1}. *${n.title}* (${n.course_code || 'N/A'})`);
    bot.sendMessage(chatId, `🧠 Smart search results for "${q}" (mode: ${data.mode}):\n\n${lines.join('\n')}`, { parse_mode: 'Markdown' });
  } catch (err) {
    console.error(err);
    bot.sendMessage(chatId, '⚠️ Smart search failed. Please try again later.');
  }
});

// ---------------------------------------------------------------------------
// /summarize <noteId> — FR18: AI summarization exposed via bot
// ---------------------------------------------------------------------------
bot.onText(/\/summarize (.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const noteId = match[1].trim();

  try {
    const res = await fetch(`${API_BASE_URL}/api/notes/${noteId}`);
    if (!res.ok) return bot.sendMessage(chatId, '❌ Note not found. Use /search to find a note ID first.');

    const { note } = await res.json();
    if (!note.summary) return bot.sendMessage(chatId, 'This note does not have a summary yet. Generate one on the web app first.');

    const trimmed = note.summary.length > 3500 ? note.summary.slice(0, 3500) + '…' : note.summary;
    bot.sendMessage(chatId, `📄 *${note.title}*\n\n${trimmed}`, { parse_mode: 'Markdown' });
  } catch (err) {
    console.error(err);
    bot.sendMessage(chatId, '⚠️ Could not fetch that note.');
  }
});

// ---------------------------------------------------------------------------
// /mynotifications — recent notifications for the linked user
// ---------------------------------------------------------------------------
bot.onText(/\/mynotifications/, async (msg) => {
  const chatId = msg.chat.id;
  const userId = await requireLinkedUser(chatId);
  if (!userId) return bot.sendMessage(chatId, 'Please link your account first with /link <code>.');

  try {
    const { rows } = await query(
      'SELECT title, body, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 5',
      [userId]
    );
    if (!rows.length) return bot.sendMessage(chatId, 'No notifications yet.');

    const lines = rows.map((n) => `🔔 *${n.title}*\n${n.body || ''}`);
    bot.sendMessage(chatId, lines.join('\n\n'), { parse_mode: 'Markdown' });
  } catch (err) {
    console.error(err);
    bot.sendMessage(chatId, '⚠️ Could not fetch notifications.');
  }
});

bot.on('polling_error', (err) => console.error('Polling error:', err.message));

module.exports = bot;
